services:
  bytebunker-backend-postgres:
    image: 'postgres:16.2'
    restart: always
    environment:
      POSTGRES_USER: "sqluser"
      POSTGRES_PASSWORD: "sqluser"
      POSTGRES_DB: "bytebunker"
    ports:
      - '4100:5432'
    volumes:
      - bytebunker-backend-postgres:/var/lib/postgresql/data
volumes:
  bytebunker-backend-postgres:
