services:
  bytebunker-backend-postgres:
    image: 'postgres:16.2'
    restart: always
    environment:
      POSTGRES_USER: "bytebunker"
      POSTGRES_PASSWORD: "bytebunker"
      POSTGRES_DB: "bytebunker"
    ports:
      - '5432:5432'
    volumes:
      - bytebunker-backend-postgres:/var/lib/postgresql/data
  bytebunker-backend-minio:
    image: 'minio/minio:latest'
    restart: always
    command: server /data --console-address ":9001"
    volumes:
      - bytebunker-backend-minio:/data
    environment:
      MINIO_ROOT_USER: "bytebunker"
      MINIO_ROOT_PASSWORD: "bytebunker"
    ports:
      - "9000:9000"
      - "9001:9001"
  bytebunker-backend-neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtest
    volumes:
      - bytebunker-backend-neo4j-data:/data
      - bytebunker-backend-neo4j-logs:/logs
  bytebunker-backend-keydb:
    image: eqalpha/keydb:latest
    entrypoint: [ "keydb-server" ]
    command: [ "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - bytebunker-backend-keydb-data:/data
volumes:
  bytebunker-backend-postgres:
  bytebunker-backend-minio:
  bytebunker-backend-neo4j-data:
  bytebunker-backend-neo4j-logs:
  bytebunker-backend-keydb-data:
