export enum NodeLabelEnum {
    AS_OBJECT = 'ASObject',
    EXTENSION = 'Extension',
    PERSON = 'Person',
    PLACE = 'Place',
    GOOGLE_PLACE = 'GooglePlace',
    AUDIO = 'Audio',
    MUSIC_RECORDING = 'MusicRecording',
    SPOTIFY_TRACK = 'SpotifyTrack',
    PODCAST_EPISODE = 'PodcastEpisode',
    SPOTIFY_EPISODE = 'SpotifyEpisode',
    VIDEO = 'Video',
    YOUTUBE_VIDEO = 'YouTubeVideo',

    ACTIVITY = 'Activity',
    GOOGLE_TIMELINE_ACTIVITY = 'GoogleTimelineActivity',
    SPOTIFY_LISTEN_ACTIVITY = 'SpotifyListenActivity',
    YOUTUBE_VIEW_ACTIVITY = 'YouTubeViewActivity',
    ACTIVITY_ARRIVE = 'Arrive',
    ACTIVITY_MOVE = 'Move',
    ACTIVITY_LISTEN = 'Listen',
    ACTIVITY_VIEW = 'View',
    ACTIVITY_EVENT = 'Event',
}
