/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Approximate accuracy radius of the location measurement, in meters. A lower value means better precision.
 */
export type Accuracy = number;
/**
 * MAC address of the access point as an integer. MAC addresses typically consist of 48 bits (6 bytes), so it is likely the value found here needs to be interpreted as a 6 byte integer (which when converted to its hexadecimal representation results in a more typical representation for MAC addresses).
 */
export type MACAddress = string;
/**
 * Strength of the signal in dBm (decibels per milliwatt) of the access point.
 */
export type Strength = number;
/**
 * Frequency of the signal (in MHz) that the access point is using.
 */
export type FrequencyMHz = number;
/**
 * Whether the device that scanned the access point is connected to it.
 */
export type IsConnected = boolean;
/**
 * List of Wi-Fi access points found with the scan.
 */
export type AccessPoints = AccessPoint[];
/**
 * Type of activity detected.
 */
export type ActivityType = ActivityType1 & ActivityType2;
export type ActivityType1 =
    | ExitingVehicle
    | InBus
    | InCar
    | InFourWheelerVehicle
    | InRailVehicle
    | InRoadVehicle
    | InTwoWheelerVehicle
    | InVehicle
    | OnBicycle
    | OnFoot
    | Running
    | Still
    | Tilting
    | Walking
    | Unknown;
/**
 * The device is exiting a vehicle.
 */
export type ExitingVehicle = 'EXITING_VEHICLE';
/**
 * The device is in a bus.
 */
export type InBus = 'IN_BUS';
/**
 * The device is in a car.
 */
export type InCar = 'IN_CAR';
/**
 * The device is in a four-wheeler vehicle.
 */
export type InFourWheelerVehicle = 'IN_FOUR_WHEELER_VEHICLE';
/**
 * The device is in a rail vehicle.
 */
export type InRailVehicle = 'IN_RAIL_VEHICLE';
/**
 * The device is in a road vehicle.
 */
export type InRoadVehicle = 'IN_ROAD_VEHICLE';
/**
 * The device is in a two-wheeler vehicle.
 */
export type InTwoWheelerVehicle = 'IN_TWO_WHEELER_VEHICLE';
/**
 * The device is in a vehicle, such as a car.
 */
export type InVehicle = 'IN_VEHICLE';
/**
 * The device is on a bicycle.
 */
export type OnBicycle = 'ON_BICYCLE';
/**
 * The device is on a user who is walking or running.
 */
export type OnFoot = 'ON_FOOT';
/**
 * The device is on a user who is running.
 */
export type Running = 'RUNNING';
/**
 * The device is still (not moving).
 */
export type Still = 'STILL';
/**
 * The device angle relative to gravity changed significantly. This often occurs when a device is picked up from a desk or a user who is sitting stands up.
 */
export type Tilting = 'TILTING';
/**
 * The device is on a user who is walking.
 */
export type Walking = 'WALKING';
/**
 * Unable to detect the current activity.
 */
export type Unknown = 'UNKNOWN';
export type ActivityType2 = string;
/**
 * Value from 0 to 100 indicating the likelihood that the user is performing this activity.
 * The larger the value, the more consistent the data used to perform the classification is with the detected activity.
 * Multiple activities may have high confidence values. For example, the `ON_FOOT` may have a confidence of 100 while the `RUNNING` activity may have a confidence of 95. The sum of the confidences of all detected activities for a classification does not have to be <= 100 since some activities are not mutually exclusive (for example, you can be walking while in a bus) and some activities are hierarchical (`ON_FOOT` is a generalization of `WALKING` and `RUNNING`).
 */
export type Confidence = number;
/**
 * Type of the property.
 */
export type Type = string;
/**
 * Name of the property.
 */
export type Name = string;
/**
 * Integer value of the property.
 */
export type IntegerValue = number;
/**
 * List of candidate detected activities with their associated confidence.
 */
export type Activity1 = Activity2[];
/**
 * Timestamp (as an ISO 8601 string) of the activity.
 */
export type Timestamp = string;
/**
 * Detected activity information at this location, as a list of activity records at slightly different timestamps but all associated with this location record.
 */
export type Activity = ActivityRecord[];
/**
 * Altitude above the WGS84 reference ellipsoid, in meters.
 */
export type Altitude = number;
/**
 * Whether the device was charging its battery or not at the time of the record.
 */
export type BatteryCharging = boolean;
/**
 * Common values found are: `PRIMARY`, `UNKNOWN`.
 */
export type DeviceDesignation = 'PRIMARY' | 'UNKNOWN';
/**
 * Integer identifier (specific to Location History) associated with the device that uploaded the location. Refer to `deviceSettings` in Settings.json for information about the device with this `deviceTag`.
 */
export type DeviceTag = number;
export type DeviceTimestamp = string;
/**
 * Form factor (device type) from which the location record originated.
 * Common values are: `PHONE`, `TABLET`.
 */
export type FormFactor = 'PHONE' | 'TABLET';
/**
 * Heading in degrees east of true north, from 0 to 359.
 */
export type Heading = number;
export type InferredLocation = LocationRecord[];
/**
 * WGS84 Latitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -900000000 to +900000000 (divide value by 10^7 for the usual range -90° to +90°).
 */
export type Latitude = number;
/**
 * Timestamp (as an ISO 8601 string) of the location metadata.
 */
export type Timestamp1 = string;
/**
 * Additional location metadata. List of different Wi-Fi scans associated with this location record.
 */
export type LocationMetadata = LocationMetadata1[];
/**
 * WGS84 Longitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -1800000000 to +1800000000 (divide value by 10^7 for the usual range -180° to +180°).
 */
export type Longitude = number;
/**
 * The version of the device's operating system that provided this record. In Android devices, this corresponds to the API Level (e.g. 28 is Android 9 *Pie*).
 */
export type OSLevel = number;
/**
 * Google Maps [Place ID](https://developers.google.com/maps/documentation/places/web-service/place-id) of the location.
 */
export type PlaceID = string;
/**
 * Platform of the device that provided this record. Valid values are: `ANDROID`, `IOS` and `UNKNOWN`.
 */
export type PlatformType = 'ANDROID' | 'IOS' | 'UNKNOWN';
export type ServerTimestamp = string;
/**
 * Source (technology) that provided the location information for this record.
 * Common values are: `WIFI`, `CELL`, `GPS`, `UNKNOWN` (note: sometimes found in lowercase).
 */
export type Source = 'WIFI' | 'wifi' | 'CELL' | 'cell' | 'GPS' | 'gps' | 'UNKNOWN' | 'unknown';
/**
 * Timestamp (as an ISO 8601 string) of the record.
 */
export type Timestamp2 = string;
/**
 * Timestamp of the record as a [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time) in milliseconds.
 */
export type TimestampMilliseconds = string;
/**
 * Measured velocity (ground speed) in meters per second.
 */
export type Velocity = number;
/**
 * Calculated accuracy of the location's altitude measurement, in meters. A lower value means better precision.
 */
export type VerticalAccuracy = number;
/**
 * List of all available location records, in chronological order.
 */
export type Locations = LocationRecord[];

/**
 * The `Records.json` file in a Google Takeout Location History extraction. Contains raw Location History information from the user's account.
 */
export interface Records {
    locations: Locations;
    [k: string]: unknown;
}
/**
 * A specific location record. Contains the information obtained from a user's device at a specific moment in time and at a given location.
 */
export interface LocationRecord {
    accuracy?: Accuracy;
    activeWifiScan?: ActiveWiFiScan;
    activity?: Activity;
    altitude?: Altitude;
    batteryCharging?: BatteryCharging;
    deviceDesignation?: DeviceDesignation;
    deviceTag?: DeviceTag;
    deviceTimestamp?: DeviceTimestamp;
    formFactor?: FormFactor;
    heading?: Heading;
    inferredLocation?: InferredLocation;
    latitudeE7?: Latitude;
    locationMetadata?: LocationMetadata;
    longitudeE7?: Longitude;
    osLevel?: OSLevel;
    placeId?: PlaceID;
    platformType?: PlatformType;
    serverTimestamp?: ServerTimestamp;
    source?: Source;
    timestamp?: Timestamp2;
    timestampMs?: TimestampMilliseconds;
    velocity?: Velocity;
    verticalAccuracy?: VerticalAccuracy;
    [k: string]: unknown;
}
/**
 * Information about the access points found in a Wi-Fi scan done by the device and associated with this location record.
 */
export interface ActiveWiFiScan {
    accessPoints?: AccessPoints;
    [k: string]: unknown;
}
/**
 * Information about a specific wireless access point or router.
 */
export interface AccessPoint {
    mac?: MACAddress;
    strength?: Strength;
    frequencyMhz?: FrequencyMHz;
    isConnected?: IsConnected;
    [k: string]: unknown;
}
/**
 * Activity information for a location at a given timestamp.
 */
export interface ActivityRecord {
    activity?: Activity1;
    timestamp?: Timestamp;
    [k: string]: unknown;
}
/**
 * A detected activity with an associated confidence. Descriptions partially based on: <https://developers.google.com/android/reference/com/google/android/gms/location/DetectedActivity>
 */
export interface Activity2 {
    type?: ActivityType;
    confidence?: Confidence;
    extra?: ExtraActivityInformation;
    [k: string]: unknown;
}
/**
 * Generic object containing extra information about an activity, in the form of a property with a type, a name, and a value. So far only the property with name `vehicle_personal_confidence` has been encountered.
 */
export interface ExtraActivityInformation {
    type?: Type;
    name?: Name;
    intVal?: IntegerValue;
    [k: string]: unknown;
}
/**
 * Information about a Wi-Fi scan done by the device at a given timestamp.
 */
export interface LocationMetadata1 {
    timestamp?: Timestamp1;
    wifiScan?: WiFiScan;
    [k: string]: unknown;
}
/**
 * Information about the access points found in a Wi-Fi scan done by the device.
 */
export interface WiFiScan {
    accessPoints?: AccessPoints;
    [k: string]: unknown;
}
