/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Timestamp (as an ISO 8601 string) when Location History was first available on this Google account.
 */
export type CreatedTime = string;
/**
 * Timestamp (as an ISO 8601 string) when any Location History setting was last modified on this Google account.
 */
export type ModifiedTime = string;
/**
 * Whether Location History is enabled on this Google account (controlled in the [Activity Controls](https://myactivity.google.com/activitycontrols?settings=location) page).
 */
export type HistoryEnabled = boolean;
/**
 * Integer identifier (specific to Location History) of the device.
 */
export type DeviceTag = number;
/**
 * Whether this device is configured to report Location History information (controlled in the [Activity Controls](https://myactivity.google.com/activitycontrols?settings=location) page).
 */
export type ReportingEnabled = boolean;
/**
 * Two-letter [ISO 3166 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
 */
export type LegalCountryCode = string;
/**
 * Pretty name of the device, recommended for user-facing applications.
 */
export type DevicePrettyName = string;
/**
 * Platform of the device. Valid values are: `ANDROID`, `IOS` and `UNKNOWN`.
 */
export type PlatformType = 'ANDROID' | 'IOS' | 'UNKNOWN';
/**
 * Timestamp (as an ISO 8601 string) of the first time this device was available for Location History reporting on this Google account.
 */
export type DeviceCreationTime = string;
/**
 * Time that Location History reporting was enabled or disabled for the last time on this Google account.
 */
export type ReportingEnabledModificationTime = string;
/**
 * The version of the device's operating system (only applies to Android devices). Corresponds to the API Level (e.g. 28 is Android 9 *Pie*).
 */
export type AndroidOSLevel = number;
/**
 * Manufacturer of the device.
 */
export type Manufacturer = string;
/**
 * Brand of the device.
 */
export type Brand = string;
/**
 * Product name of the device.
 */
export type Product = string;
/**
 * Name of the device.
 */
export type Device = string;
/**
 * Model of the device.
 */
export type Model = string;
/**
 * Whether the device is considered low-ram.
 */
export type IsLowRam = boolean;
/**
 * List of devices associated with the Location History information on this Google account.
 */
export type DeviceSettings = DeviceSettings1[];
/**
 * Number of days the Location History information is retained in this Google account. Corresponds to the *Auto-delete* setting in the [Activity Controls](https://myactivity.google.com/activitycontrols?settings=location) page.
 * This value should be ignored if [#/properties/hasSetRetention] is false.
 */
export type RetentionWindowDays = number;
/**
 * Whether this Google account has any reported Location History information.
 */
export type HasReportedLocations = boolean;
/**
 * Whether this Google account has configured the auto-delete setting (retention) for the Location History data. Corresponds to the *Auto-delete* setting in the [Activity Controls](https://myactivity.google.com/activitycontrols?settings=location) page.
 * See also [#/properties/retentionWindowDays].
 */
export type HasSetRetention = boolean;

/**
 * The `Settings.json` file in a Google Takeout Location History extraction. Contains information about the Google account settings related to Location History, information about the devices associated, and other auxiliary metadata.
 */
export interface Settings {
    createdTime?: CreatedTime;
    modifiedTime?: ModifiedTime;
    historyEnabled?: HistoryEnabled;
    deviceSettings?: DeviceSettings;
    retentionWindowDays?: RetentionWindowDays;
    hasReportedLocations?: HasReportedLocations;
    hasSetRetention?: HasSetRetention;
    [k: string]: unknown;
}
/**
 * Information about a device associated with the Google Location History account.
 */
export interface DeviceSettings1 {
    deviceTag?: DeviceTag;
    reportingEnabled?: ReportingEnabled;
    legalCountryCode?: LegalCountryCode;
    devicePrettyName?: DevicePrettyName;
    platformType?: PlatformType;
    deviceCreationTime?: DeviceCreationTime;
    latestLocationReportingSettingChange?: LatestLocationReportingSettingChange;
    androidOsLevel?: AndroidOSLevel;
    deviceSpec?: DeviceSpecification;
    [k: string]: unknown;
}
/**
 * Information on the latest change(s) to Location History settings on this Google account.
 */
export interface LatestLocationReportingSettingChange {
    reportingEnabledModificationTime?: ReportingEnabledModificationTime;
    [k: string]: unknown;
}
/**
 * Technical information and specifications about the device.
 */
export interface DeviceSpecification {
    manufacturer?: Manufacturer;
    brand?: Brand;
    product?: Product;
    device?: Device;
    model?: Model;
    isLowRam?: IsLowRam;
    [k: string]: unknown;
}
