/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier for the device that generated the data.
 */
export type DeviceID = string;
/**
 * The score assigned to the place.
 */
export type Score = number;
/**
 * The number of location buckets associated with the place.
 */
export type NumberOfBuckets = number;
/**
 * The span of the buckets in days.
 */
export type BucketSpan = number;
/**
 * Latitude coordinate of the point. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -900000000 to +900000000 (divide value by 10^7 for the usual range -90° to +90°).
 */
export type Latitude = number;
/**
 * Longitude coordinate of the point. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -1800000000 to +1800000000 (divide value by 10^7 for the usual range -180° to +180°).
 */
export type Longitude = number;
/**
 * The unique identifier for the place.
 */
export type PlaceID = string;
/**
 * An array of place information, including score, location, and place ID.
 */
export type PlaceAggregateInformation = PlaceAggregateInfoItem[];
/**
 * The size of the window in hours for the place aggregates.
 */
export type TimeWindowSize = number;
/**
 * The ID of top place ID
 */
export type TopRankedPlaceID = string;
/**
 * An array of place IDs for the top-ranked places.
 */
export type TopRankedPlaces = TopRankedPlaceID[];
/**
 * The start time of the processing window.
 */
export type StartTime = string;
/**
 * The end time of the processing window.
 */
export type EndTime = string;
/**
 * The platform that generated the data.
 */
export type DevicePlatform = string;
/**
 * The accuracy of the position in millimeters.
 */
export type SignalPositionAccuracy = number;
/**
 * The altitude of the position in meters.
 */
export type Altitude = number;
/**
 * The source of the position data.
 */
export type SignalPositionSource = string;
/**
 * Speed in meters per second.
 */
export type Speed = number;
/**
 * The timestamp of the position data.
 */
export type Timestamp = string;
/**
 * The type of the detected activity. This could re-use the `#/$defs/activityType` from Records schema later.
 */
export type ActivityType = string;
/**
 * The probability of the detected activity.
 */
export type Probability = number;
/**
 * An array of detected activities, including activity type and probability.
 */
export type DetectedActivities = DetectedActivityItem[];
/**
 * The timestamp of the activity record.
 */
export type Timestamp1 = string;
/**
 * The delivery time of the wifi scan.
 */
export type DeliveryTime = string;
/**
 * The mac address of the wifi device.
 */
export type MACAddress = string;
/**
 * The raw RSSI of the wifi device.
 */
export type RawRSSI = number;
/**
 * An array of wifi devices, including mac address and raw RSSI.
 */
export type WifiDevices = WifiDevice[];
/**
 * The source of the wifi scan data.
 */
export type WifiScanSource = string;
/**
 * An additional timestamp associated with the raw signal.
 */
export type AdditionalTimestamp = string;
/**
 * List of all timeline edits.
 */
export type TimelineEdits = TimelineEditInformation[];

/**
 * This schema outlines the structure of timeline edits data, encompassing device information, place visit aggregates, and raw signal data from the device.
 */
export interface TimelineEditsSchema {
    timelineEdits: TimelineEdits;
    [k: string]: unknown;
}
/**
 * Various information about the timeline edit, including device ID, place aggregates, and raw signal data.
 */
export interface TimelineEditInformation {
    deviceId: DeviceID;
    placeAggregates?: PlaceAggregates;
    rawSignal?: RawSignal;
    [k: string]: unknown;
}
/**
 * Aggregated information about places visited by the device.
 */
export interface PlaceAggregates {
    placeAggregateInfo: PlaceAggregateInformation;
    windowSizeHrs: TimeWindowSize;
    topRankedPlacesPlaceIds: TopRankedPlaces;
    processWindow: ProcessWindow;
    metadata: Metadata;
    [k: string]: unknown;
}
/**
 * The place aggregate info containing score, location, place ID, and other details.
 */
export interface PlaceAggregateInfoItem {
    score: Score;
    numBucketsWithLocation: NumberOfBuckets;
    bucketSpanDays: BucketSpan;
    point: Point;
    placeId: PlaceID;
    placePoint: Point;
    [k: string]: unknown;
}
/**
 * The geographical point.
 */
export interface Point {
    latE7: Latitude;
    lngE7: Longitude;
    [k: string]: unknown;
}
/**
 * The start and end time of the processing window.
 */
export interface ProcessWindow {
    startTime: StartTime;
    endTime: EndTime;
    [k: string]: unknown;
}
/**
 * Metadata about the data object.
 */
export interface Metadata {
    platform: DevicePlatform;
    [k: string]: unknown;
}
/**
 * Raw signal data from the device.
 */
export interface RawSignal {
    signal?: Signal;
    additionalTimestamp?: AdditionalTimestamp;
    metadata?: Metadata;
    [k: string]: unknown;
}
/**
 * The signal data, including position, activity record, and wifi scan.
 */
export interface Signal {
    position?: Position;
    activityRecord?: ActivityRecord;
    wifiScan?: WifiScanData;
    [k: string]: unknown;
}
/**
 * The position data, including point, accuracy, altitude, source, and timestamp.
 */
export interface Position {
    point: Point;
    accuracyMm?: SignalPositionAccuracy;
    altitudeMeters?: Altitude;
    source?: SignalPositionSource;
    speedMetersPerSecond?: Speed;
    timestamp: Timestamp;
    [k: string]: unknown;
}
/**
 * The activity record data, including detected activities and timestamp.
 */
export interface ActivityRecord {
    detectedActivities: DetectedActivities;
    timestamp: Timestamp1;
    [k: string]: unknown;
}
/**
 * The detected activity item info containing activity type and probability.
 */
export interface DetectedActivityItem {
    activityType: ActivityType;
    probability: Probability;
    [k: string]: unknown;
}
/**
 * The wifi scan data, including delivery time, devices, and source.
 */
export interface WifiScanData {
    deliveryTime: DeliveryTime;
    devices: WifiDevices;
    source?: WifiScanSource;
    [k: string]: unknown;
}
/**
 * The wifi device info containing mac address and raw RSSI.
 */
export interface WifiDevice {
    mac: MACAddress;
    rawRssi: RawRSSI;
    [k: string]: unknown;
}
