/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { PlaceConfidenceEnum } from './place-confidence.enum.js';

/**
 * Encapsulates either an ![#/$defs/activitySegment] or a ![#/$defs/placeVisit], depending on the single key found.
 */
export type TimelineObject =
    | {
          activitySegment: ActivitySegment;
      }
    | {
          placeVisit: PlaceVisit;
      };
/**
 * Latitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -900000000 to +900000000 (divide value by 10^7 for the usual range -90° to +90°).
 */
export type Latitude = number;
/**
 * Longitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -1800000000 to +1800000000 (divide value by 10^7 for the usual range -180° to +180°).
 */
export type Longitude = number;
/**
 * Address of the location.
 */
export type Address = string;
/**
 * Name of the location.
 */
export type Name = string;

/**
 * Place type based on semantic information specific to the user.
 */
export enum SpecificSemanticTypeEnum {
    /**
     * The place has been designated as 'Home' by the user. See: [Set or change your home & work addresses](https://support.google.com/maps/answer/3093979?hl=en).
     */
    HOME = 'TYPE_HOME',
    /**
     * The place has been designated as 'Work' by the user. See: [Set or change your home & work addresses](https://support.google.com/maps/answer/3093979?hl=en).
     */
    WORK = 'TYPE_WORK',
    /**
     * The user has searched for this place in the past.
     */
    SEARCHED_ADDRESS = 'TYPE_SEARCHED_ADDRESS',
    /**
     * The place has been given a private label by the user. See: [Give a place a private label](https://support.google.com/maps/answer/6257830?hl=en).
     */
    ALIASED_LOCATION = 'TYPE_ALIASED_LOCATION',
}

/**
 * Approximate accuracy radius of the location measurement, in meters. A lower value means better precision.
 */
export type AccuracyInMeters = number;
export type LocationConfidence = number;
export type IsCurrentLocation = boolean;
export type CalibratedProbability = number;
/**
 * Integer identifier (specific to Location History) associated with the device that obtained the location. Refer to `deviceSettings` in Settings.json for information about the device with this `deviceTag`.
 */
export type DeviceTag = number;
export type StartTimestamp = string;
export type EndTimestamp = string;
/**
 * Distance traveled during the activity, in meters.
 */
export type Distance = number;

/**
 * Best match activity type. Corresponds to the activity type with the highest probability in [#/$defs/activitySegment/properties/activities].
 */
export enum ActivityTypeEnum {
    UNKNOWN_ACTIVITY_TYPE = 'UNKNOWN_ACTIVITY_TYPE',
    STILL = 'STILL',
    WALKING = 'WALKING',
    CYCLING = 'CYCLING',
    IN_VEHICLE = 'IN_VEHICLE',
    FLYING = 'FLYING',
    RUNNING = 'RUNNING',
    IN_BUS = 'IN_BUS',
    IN_TRAIN = 'IN_TRAIN',
    IN_SUBWAY = 'IN_SUBWAY',
    IN_TRAM = 'IN_TRAM',
    IN_FERRY = 'IN_FERRY',
    IN_CABLECAR = 'IN_CABLECAR',
    IN_FUNICULAR = 'IN_FUNICULAR',
    HIKING = 'HIKING',
    KAYAKING = 'KAYAKING',
    KITESURFING = 'KITESURFING',
    ROWING = 'ROWING',
    SAILING = 'SAILING',
    SKATING = 'SKATING',
    SKIING = 'SKIING',
    SKATEBOARDING = 'SKATEBOARDING',
    SLEDDING = 'SLEDDING',
    SNOWBOARDING = 'SNOWBOARDING',
    SNOWMOBILE = 'SNOWMOBILE',
    SNOWSHOEING = 'SNOWSHOEING',
    SURFING = 'SURFING',
    SWIMMING = 'SWIMMING',
    WALKING_NORDIC = 'WALKING_NORDIC',
    IN_PASSENGER_VEHICLE = 'IN_PASSENGER_VEHICLE',
    MOTORCYCLING = 'MOTORCYCLING',
    BOATING = 'BOATING',
    IN_WHEELCHAIR = 'IN_WHEELCHAIR',
    HORSEBACK_RIDING = 'HORSEBACK_RIDING',
    IN_GONDOLA_LIFT = 'IN_GONDOLA_LIFT',
    CATCHING_POKEMON = 'CATCHING_POKEMON',
    IN_TAXI = 'IN_TAXI',
    PARAGLIDING = 'PARAGLIDING',
}

/**
 * Probability (or confidence) that the activity type is correct, in the range 0 to 100.
 */
export type Probability = number;
/**
 * List of all the considered candidate activity types and their probabilities. The sum of all the probabilities is always <= 100.
 */
export type Activities = Activity[];
/**
 * Confidence that the chosen activity type (see [#/$defs/activitySegment/properties/activityType]) is correct. One of: `LOW`, `MEDIUM`, `HIGH` or `UNKNOWN_CONFIDENCE`. Activities that have been manually confirmed always have a confidence of `HIGH`.
 */
export type Confidence = 'LOW' | 'MEDIUM' | 'HIGH' | 'UNKNOWN_CONFIDENCE';
export type Waypoints = Waypoint[];
/**
 * Source of the location data of the path. Either `BACKFILLED` or `INFERRED`.
 */
export type Source = 'BACKFILLED' | 'INFERRED';
/**
 * Total distance of the path, in meters.
 */
export type DistanceInMeters = number;
export type TravelMode = 'WALK' | 'DRIVE' | 'BICYCLE';
export type ConfidenceNumber = number;
export type DurationString = string;
/**
 * Google Maps [Place ID](https://developers.google.com/maps/documentation/places/web-service/place-id)
 */
export type PlaceID = string;
export type RoadSegment = RoadSegment1[];
/**
 * Approximate accuracy radius of the location measurement, in meters. A lower value means better precision.
 */
export type AccuracyInMeters1 = number;
/**
 * Timestamp of the point.
 */
export type Timestamp = string;
/**
 * List of all the recorded points that form the path.
 */
export type Points = Point[];
/**
 * Source of the location data of the path. One of `BACKFILLED`, `INFERRED`, or `RESNAPPED_FOR_EDIT`.
 */
export type Source1 = 'BACKFILLED' | 'INFERRED' | 'RESNAPPED_FOR_EDIT';
/**
 * Distance traveled with the path, in meters.
 */
export type DistanceInMeters1 = number;
/**
 * List of locations of the transit stops used.
 */
export type TransitStops = Location[];
/**
 * Name of the transit line.
 */
export type Name1 = string;
/**
 * Color of the transit line in hexadecimal in the form *RRGGBB*.
 */
export type HexadecimalRGBColor = string;
export type ScheduleArrivalTimestamp = string;
export type ScheduledDepartureTimestamp = string;
export type RealtimeArrivalTimestamp = string;
export type RealtimeDepartureTimestamp = string;
/**
 * Time information (departure and arrival times, both real and scheduled) for each transit stop used.
 */
export type StopTimesInfo = StopTimeInfo[];
/**
 * Source of the location data of the transit path. Either `BACKFILLED` or `INFERRED`.
 */
export type Source2 = 'BACKFILLED' | 'INFERRED';
export type Confidence2 = number;
/**
 * Distance traveled with the transit path, in meters.
 */
export type DistanceInMeters2 = number;
export type Method = 'PERSONAL_VEHICLE_CONFIDENCE' | 'END_OF_ACTIVITY_SEGMENT' | 'EXITING_VEHICLE_SIGNAL' | 'UNDEFINED';
export type LocationSource = 'FROM_RAW_LOCATION' | 'NOT_FROM_RAW_LOCATION' | 'UNKNOWN';
export type Timestamp1 = string;
/**
 * Whether the user has manually edited the activity segment. Can be `NOT_CONFIRMED` or `CONFIRMED`.
 */
export type EditConfirmationStatus = 'NOT_CONFIRMED' | 'CONFIRMED';
export type Confidence3 = number;
export type EditOperation1 =
    | 'CREATE'
    | 'CONFIRM'
    | 'MODIFY_TIME'
    | 'MODIFY_LOCATION'
    | 'MODIFY_ACTIVITY_TYPE'
    | 'MODIFY_UNCHANGED';
export type EditOperation = EditOperation1[];
export type UIActivitySegmentConfiguration =
    | 'DEFAULT_ACTIVITY_SEGMENT_CONFIGURATION'
    | 'UNPERSONALIZED_EDIT_ACTIVITY_SEGMENT'
    | 'UNKNOWN_UI_ACTIVITY_SEGMENT_CONFIGURATION';
export type UIPlaceVisitConfiguration =
    | 'DEFAULT_PLACE_VISIT_CONFIGURATION'
    | 'YES_NO_OTHER_PLACE_VISIT'
    | 'FORCED_NEIGHBORHOOD'
    | 'UNPERSONALIZED_EDIT_PLACE_VISIT';
export type EditEvent = EditEvent1[];
export type PlaceVisitCandidate = OriginalCandidates1[];
export type LastEditedTimestamp = string;
/**
 * Latitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -900000000 to +900000000 (divide value by 10^7 for the usual range -90° to +90°).
 */
export type CenterLatitude = number;
/**
 * Longitude coordinate of the location. Degrees multiplied by 10^7 and rounded to the nearest integer, in the range -1800000000 to +1800000000 (divide value by 10^7 for the usual range -180° to +180°).
 */
export type CenterLongitude = number;
export type VisitConfidence = number;
export type VisitConfidence1 = number;
export type OtherCandidateLocations = Location[];
export type ChildVisits = PlaceVisit[];
export type SectionID = string;
/**
 * Level (depth) of this place visit. This value increases by 1 with each recursive access to a [#/$defs/placeVisit/properties/childVisits] entry.
 */
export type PlaceVisitLevel = number;
/**
 * Whether the user has manually edited the place visit. Can be `NOT_CONFIRMED` or `CONFIRMED`.
 */
export type EditConfirmationStatus1 = 'NOT_CONFIRMED' | 'CONFIRMED';
export type LastEditedTimestamp1 = string;
/**
 * Can be `SINGLE_PLACE`.
 */
export type PlaceVisitType = 'SINGLE_PLACE';
/**
 * One of `MAIN` or `TRANSITIONAL`.
 */
export type PlaceVisitImportance = 'MAIN' | 'TRANSITIONAL';
export type LocationAssertionType = 'AREA' | 'WITHIN_OR_AT';
export type AtTime = string;
export type DetectionTime = string;
export type Fingerprint = string;
/**
 * List of all available semantic information, in chronological order. Each item in the list is either an ![#/$defs/activitySegment] or a ![#/$defs/placeVisit], encapsulated in a generic ![#/properties/timelineObjects/items].
 */
export type TimelineObjects = TimelineObject[];

/**
 * A Semantic Location History JSON file in a Google Takeout Location History extraction. Contains Semantic Location History information from the user's account. Typically this will be a file containing data for a single month, with a name such as `2021_JANUARY.json`.
 */
export interface SemanticLocationHistory {
    timelineObjects: TimelineObjects;
}

export interface Location {
    latitudeE7?: Latitude;
    longitudeE7?: Longitude;
    placeId?: PlaceID;
    address?: Address;
    name?: Name;
    semanticType?: SpecificSemanticTypeEnum;
    accuracyMetres?: AccuracyInMeters;
    locationConfidence?: LocationConfidence;
    isCurrentLocation?: IsCurrentLocation;
    calibratedProbability?: CalibratedProbability;
    sourceInfo?: SourceInformation;
}

/**
 * An activity involving changes in location, usually a journey from one place to another, such as a walk, a car drive, a bus ride, or a flight.
 */
export interface ActivitySegment {
    startLocation?: Location;
    endLocation?: Location;
    duration?: DurationObject;
    distance?: Distance;
    activityType?: ActivityTypeEnum;
    activities?: Activities;
    confidence?: Confidence;
    waypointPath?: WaypointPath;
    simplifiedRawPath?: SimplifiedRawPath;
    transitPath?: TransitPath;
    parkingEvent?: ParkingEvent;
    editConfirmationStatus?: EditConfirmationStatus;
    editActionMetadata?: EditActionMetadata;
    lastEditedTimestamp?: LastEditedTimestamp;

    [k: string]: unknown;
}

/**
 * Information on the source that provided the location.
 */
export interface SourceInformation {
    deviceTag?: DeviceTag;

    [k: string]: unknown;
}

export interface Activity {
    activityType?: ActivityTypeEnum;
    probability?: Probability;

    [k: string]: unknown;
}

export interface WaypointPath {
    waypoints?: Waypoints;
    source?: Source;
    distanceMeters?: DistanceInMeters;
    travelMode?: TravelMode;
    confidence?: ConfidenceNumber;
    roadSegment?: RoadSegment;

    [k: string]: unknown;
}

export interface Waypoint {
    latE7?: Latitude;
    lngE7?: Longitude;

    [k: string]: unknown;
}

export interface RoadSegment1 {
    duration?: DurationString;
    placeId?: PlaceID;

    [k: string]: unknown;
}

export interface SimplifiedRawPath {
    points?: Points;
    source?: Source1;
    distanceMeters?: DistanceInMeters1;

    [k: string]: unknown;
}

export interface Point {
    latE7?: Latitude;
    lngE7?: Longitude;
    accuracyMeters?: AccuracyInMeters1;
    timestamp?: Timestamp;

    [k: string]: unknown;
}

/**
 * Path taken in a public transit system, such as a bus or a metro.
 */
export interface TransitPath {
    transitStops?: TransitStops;
    name?: Name1;
    hexRgbColor?: HexadecimalRGBColor;
    linePlaceId?: PlaceID;
    stopTimesInfo?: StopTimesInfo;
    source?: Source2;
    confidence?: Confidence2;
    distanceMeters?: DistanceInMeters2;

    [k: string]: unknown;
}

/**
 * Departure and/or arrival time information (both real and scheduled) for a stop at a transit line.
 */
export interface StopTimeInfo {
    scheduleArrivalTimestamp?: ScheduleArrivalTimestamp;
    scheduledDepartureTimestamp?: ScheduledDepartureTimestamp;
    realtimeArrivalTimestamp?: RealtimeArrivalTimestamp;
    realtimeDepartureTimestamp?: RealtimeDepartureTimestamp;

    [k: string]: unknown;
}

export interface ParkingEvent {
    location?: Location;
    method?: Method;
    locationSource?: LocationSource;
    timestamp?: Timestamp1;

    [k: string]: unknown;
}

export interface EditActionMetadata {
    activitySegment?: ActivitySegment1;
    placeVisitSegment?: PlaceVisitSegment;
    editHistory?: EditHistory;
    originalCandidates?: OriginalCandidates;

    [k: string]: unknown;
}

export interface ActivitySegment1 {
    activityType?: ActivityTypeEnum;
    activityConfidence?: Confidence3;

    [k: string]: unknown;
}

export interface PlaceVisitSegment {
    location?: Location;

    [k: string]: unknown;
}

export interface EditHistory {
    editEvent?: EditEvent;

    [k: string]: unknown;
}

export interface EditEvent1 {
    editOperation?: EditOperation;
    uiConfiguration?: UIConfiguration;

    [k: string]: unknown;
}

export interface UIConfiguration {
    uiActivitySegmentConfiguration?: UIActivitySegmentConfiguration;
    uiPlaceVisitConfiguration?: UIPlaceVisitConfiguration;

    [k: string]: unknown;
}

export interface OriginalCandidates {
    placeVisitSegment?: PlaceVisitSegment1;

    [k: string]: unknown;
}

export interface PlaceVisitSegment1 {
    placeVisitCandidate?: PlaceVisitCandidate;

    [k: string]: unknown;
}

export interface OriginalCandidates1 {
    location?: Location;

    [k: string]: unknown;
}

/**
 * A visit or stay at a place in a fixed location for a duration of time, such as a stay at home, at work, a visit to a shopping mall, or to a restaurant.
 */
export interface PlaceVisit {
    location?: Location;
    centerLatE7?: CenterLatitude;
    centerLngE7?: CenterLongitude;
    duration?: DurationObject;
    placeConfidence?: PlaceConfidenceEnum;
    visitConfidence?: VisitConfidence;
    locationConfidence?: VisitConfidence1;
    otherCandidateLocations?: OtherCandidateLocations;
    childVisits?: ChildVisits;
    sectionId?: SectionID;
    simplifiedRawPath?: SimplifiedRawPath1;
    placeVisitLevel?: PlaceVisitLevel;
    editConfirmationStatus?: EditConfirmationStatus1;
    editActionMetadata?: EditActionMetadata1;
    lastEditedTimestamp?: LastEditedTimestamp1;
    placeVisitType?: PlaceVisitType;
    placeVisitImportance?: PlaceVisitImportance;
    locationAssertionType?: LocationAssertionType;
    checkin?: Checkin;

    [k: string]: unknown;
}

/**
 * Duration of the place visit.
 */
export interface DurationObject {
    startTimestamp?: StartTimestamp;
    endTimestamp?: EndTimestamp;
    startTimestampMs?: StartTimestamp;
    endTimestampMs?: EndTimestamp;
}

export interface SimplifiedRawPath1 {
    points?: Points;
    source?: Source1;
    distanceMeters?: DistanceInMeters1;

    [k: string]: unknown;
}

export interface EditActionMetadata1 {
    activitySegment?: ActivitySegment1;
    placeVisitSegment?: PlaceVisitSegment;
    editHistory?: EditHistory;
    originalCandidates?: OriginalCandidates;

    [k: string]: unknown;
}

export interface Checkin {
    atTime?: AtTime;
    latestKnownLocation?: LatestKnownLocation;
    device?: Device;

    [k: string]: unknown;
}

export interface LatestKnownLocation {
    location?: Location;
    detectionTime?: DetectionTime;

    [k: string]: unknown;
}

export interface Device {
    android?: Android;

    [k: string]: unknown;
}

export interface Android {
    fingerprint?: Fingerprint;

    [k: string]: unknown;
}
