/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An ISO 8601 timestamp with timezone offset, e.g. `2024-11-22T10:53:29.000+01:00`.
 */
export type ISO8601Timestamp = string;
/**
 * A latitude/longitude pair formatted as a single string with degree symbols, e.g. `"49.7403348°, 6.650313°"` (latitude first, then longitude).
 */
export type GeoCoordinateString = string;
/**
 * Ordered list of recorded points forming the path travelled during the segment.
 */
export type TimelinePath = TimelinePathPoint[];
/**
 * Semantic classification of the place relative to the user.
 */
export type VisitSemanticType =
    | 'UNKNOWN'
    | 'HOME'
    | 'WORK'
    | 'INFERRED_HOME'
    | 'INFERRED_WORK'
    | 'SEARCHED_ADDRESS'
    | 'ALIASED_LOCATION';
/**
 * Detected activity/travel-mode type. Open enum; known values include UNKNOWN_ACTIVITY_TYPE, WALKING, RUNNING, CYCLING, HIKING, SKATING, IN_VEHICLE, IN_PASSENGER_VEHICLE, IN_BUS, IN_TRAIN, IN_SUBWAY, IN_TRAM, IN_FERRY, IN_CABLECAR, FLYING, CATCHING_POKEMON.
 */
export type ActivityType = string;
/**
 * Processed, chronologically ordered segments of the user's timeline. Each segment carries a start/end time plus exactly one of `timelinePath`, `visit`, `activity` or `timelineMemory`.
 */
export type SemanticSegments = SemanticSegment[];
/**
 * Origin of the location fix. Open enum; known values include UNKNOWN, WIFI_ONLY, GPS, CELL.
 */
export type PositionSource = string;
/**
 * Low-level activity-recognition type. Open enum; known values include UNKNOWN, STILL, WALKING, RUNNING, ON_FOOT, ON_BICYCLE, IN_VEHICLE, IN_ROAD_VEHICLE, IN_RAIL_VEHICLE, EXITING_VEHICLE, TILTING.
 */
export type ProbableActivityType = string;
/**
 * Unprocessed device signals (positions, detected activity records and Wi-Fi scans) the timeline was derived from.
 */
export type RawSignals = RawSignal[];
/**
 * User label for the place.
 */
export type FrequentPlaceLabel = 'HOME' | 'WORK';
export type CommuteDirection = 'COMMUTE_DIRECTION_HOME_TO_WORK' | 'COMMUTE_DIRECTION_WORK_TO_HOME';

/**
 * The on-device Google Maps Timeline export (`Timeline.json` / `location-history.json`), introduced in 2024 when Location History moved from the server to the device. Replaces the old per-month Semantic Location History files. Top level holds processed semantic segments, raw device signals, and an aggregated user location profile.
 */
export interface LocationHistoryTimeline {
    semanticSegments: SemanticSegments;
    rawSignals?: RawSignals;
    userLocationProfile?: UserLocationProfile;
    [k: string]: unknown;
}
/**
 * A single timeline segment. Always has `startTime`/`endTime`; the payload is one of `timelinePath`, `visit`, `activity` or `timelineMemory`.
 */
export interface SemanticSegment {
    startTime: ISO8601Timestamp;
    endTime: ISO8601Timestamp;
    /**
     * UTC offset of `startTime`, in minutes. Absent on raw `timelinePath`-only segments.
     */
    startTimeTimezoneUtcOffsetMinutes?: number;
    /**
     * UTC offset of `endTime`, in minutes.
     */
    endTimeTimezoneUtcOffsetMinutes?: number;
    timelinePath?: TimelinePath;
    visit?: Visit;
    activity?: Activity;
    timelineMemory?: TimelineMemory;
    [k: string]: unknown;
}
export interface TimelinePathPoint {
    point: GeoCoordinateString;
    time: ISO8601Timestamp;
    [k: string]: unknown;
}
/**
 * A stay at a fixed place for a duration of time.
 */
export interface Visit {
    /**
     * Nesting depth of the visit (0 = top level).
     */
    hierarchyLevel?: number;
    /**
     * Probability that this segment is a visit, in the range 0 to 1.
     */
    probability?: number;
    /**
     * True when the visit has no reliable duration.
     */
    isTimelessVisit?: boolean;
    topCandidate: VisitCandidate;
    [k: string]: unknown;
}
export interface VisitCandidate {
    /**
     * Google Maps Place ID of the candidate place.
     */
    placeId: string;
    semanticType?: VisitSemanticType;
    /**
     * Probability that this candidate is the correct place, in the range 0 to 1.
     */
    probability?: number;
    placeLocation: LatLngWrapper;
    [k: string]: unknown;
}
/**
 * Object wrapping a single coordinate string under the `latLng` key.
 */
export interface LatLngWrapper {
    latLng: GeoCoordinateString;
    [k: string]: unknown;
}
/**
 * A journey from one place to another (walk, drive, transit ride, flight, ...).
 */
export interface Activity {
    start: LatLngWrapper;
    end: LatLngWrapper;
    /**
     * Distance travelled during the activity, in meters.
     */
    distanceMeters?: number;
    /**
     * Probability that this segment is an activity, in the range 0 to 1.
     */
    probability?: number;
    topCandidate: ActivityCandidate;
    parking?: ParkingEvent;
    [k: string]: unknown;
}
export interface ActivityCandidate {
    type: ActivityType;
    /**
     * Probability that this activity type is correct, in the range 0 to 1.
     */
    probability?: number;
    [k: string]: unknown;
}
export interface ParkingEvent {
    location: LatLngWrapper;
    startTime: ISO8601Timestamp;
    [k: string]: unknown;
}
/**
 * An aggregated 'memory' such as a trip spanning multiple destinations.
 */
export interface TimelineMemory {
    trip?: Trip;
    [k: string]: unknown;
}
export interface Trip {
    /**
     * Maximum distance of the trip from its origin, in kilometers.
     */
    distanceFromOriginKms?: number;
    destinations: TripDestination[];
    [k: string]: unknown;
}
export interface TripDestination {
    identifier: {
        /**
         * Google Maps Place ID of the destination.
         */
        placeId: string;
        [k: string]: unknown;
    };
    [k: string]: unknown;
}
/**
 * A single raw device signal. Exactly one of `position`, `activityRecord` or `wifiScan` is present.
 */
export interface RawSignal {
    position?: Position;
    activityRecord?: ActivityRecord;
    wifiScan?: WiFiScan;
    [k: string]: unknown;
}
/**
 * A raw location fix. Note the capitalised `LatLng` key (unlike the lower-case `latLng` used elsewhere).
 */
export interface Position {
    LatLng: GeoCoordinateString;
    /**
     * Approximate accuracy radius of the fix, in meters. Lower is better.
     */
    accuracyMeters?: number;
    /**
     * Altitude in meters, when available.
     */
    altitudeMeters?: number;
    source?: PositionSource;
    timestamp?: ISO8601Timestamp;
    /**
     * Instantaneous speed in meters per second, when available.
     */
    speedMetersPerSecond?: number;
    [k: string]: unknown;
}
/**
 * A raw on-device activity-recognition reading with candidate activities.
 */
export interface ActivityRecord {
    probableActivities: ProbableActivity[];
    timestamp: ISO8601Timestamp;
    [k: string]: unknown;
}
export interface ProbableActivity {
    type: ProbableActivityType;
    /**
     * Confidence of this activity type, in the range 0 to 1.
     */
    confidence: number;
    [k: string]: unknown;
}
/**
 * A raw Wi-Fi scan with the access points seen at delivery time.
 */
export interface WiFiScan {
    deliveryTime: ISO8601Timestamp;
    devicesRecords?: WiFiDeviceRecord[];
    [k: string]: unknown;
}
export interface WiFiDeviceRecord {
    /**
     * MAC address of the access point, encoded as an integer.
     */
    mac: number;
    /**
     * Raw received signal strength indicator, in dBm.
     */
    rawRssi: number;
    [k: string]: unknown;
}
/**
 * Aggregated profile derived from the user's history: frequent places, frequent trips and travel persona.
 */
export interface UserLocationProfile {
    frequentPlaces?: FrequentPlace[];
    frequentTrips?: FrequentTrip[];
    persona?: Persona;
    [k: string]: unknown;
}
export interface FrequentPlace {
    /**
     * Google Maps Place ID of the frequent place.
     */
    placeId: string;
    placeLocation: GeoCoordinateString;
    label?: FrequentPlaceLabel;
    [k: string]: unknown;
}
export interface FrequentTrip {
    /**
     * Ordered Google Maps Place IDs of the waypoints along the trip.
     */
    waypointIds?: string[];
    modeDistribution?: ModeShare[];
    /**
     * Typical start time, in minutes past midnight (local).
     */
    startTimeMinutes?: number;
    /**
     * Typical end time, in minutes past midnight (local).
     */
    endTimeMinutes?: number;
    /**
     * Typical trip duration, in minutes.
     */
    durationMinutes?: number;
    /**
     * Confidence in this frequent trip, in the range 0 to 1.
     */
    confidence?: number;
    commuteDirection?: CommuteDirection;
    [k: string]: unknown;
}
export interface ModeShare {
    /**
     * Travel mode (open enum, e.g. WALKING, IN_BUS, IN_TRAIN, IN_SUBWAY, IN_PASSENGER_VEHICLE, RUNNING).
     */
    mode: string;
    /**
     * Share of trips taken with this mode, in the range 0 to 1.
     */
    rate: number;
    [k: string]: unknown;
}
/**
 * Aggregated travel-mode affinities of the user.
 */
export interface Persona {
    travelModeAffinities?: ModeAffinity[];
    [k: string]: unknown;
}
export interface ModeAffinity {
    /**
     * Travel mode (open enum, e.g. WALKING, IN_BUS, IN_PASSENGER_VEHICLE, IN_TRAIN, FLYING, CYCLING, RUNNING).
     */
    mode: string;
    /**
     * Relative affinity for this mode, in the range 0 to 1.
     */
    affinity: number;
    [k: string]: unknown;
}
