import { EXTENSION_NAME_LENGTH } from '../../../extension/extension.constant.js';

export const PIPELINE_MODULE_NAME_LENGTH = 64;
export const PIPELINE_MODULE_VERSION_LENGTH = '65535'.length;
export const PIPELINE_MODULE_IDENTIFIER_LENGTH =
    EXTENSION_NAME_LENGTH + 1 + PIPELINE_MODULE_NAME_LENGTH + 1 + PIPELINE_MODULE_VERSION_LENGTH;
