@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LANDSCAPE()

Container_Boundary(backend, "Backend (NestJS)") {
    Component(pipelineSystem, "Pipeline System", "", "")
    Component(assetModule, "Asset", "Modul", "")

    Component(activityGraphModule, "Aktivitätengraph", "Modul", "")
    Component(activitySearchModule, "Aktivitätensuche", "Modul", "")

    Component(databaseModule, "SQL-Datenbank", "Modul", "")
    Component(authUserModule, "Authentifikation/Benutzer", "Module", "")

    Component(extensionSystem, "Extension System", "", "")
    Component(settingsModule, "Einstellungen", "Modul", "")

    Component(sharedModules, "Geteilte Module", "", "")

    Rel(pipelineSystem, activityGraphModule, "Verwendet")
    Rel(pipelineSystem, assetModule, "Verwendet")
    Rel(pipelineSystem, databaseModule, "Verwendet")

    Rel(activitySearchModule, activityGraphModule, "Verwendet")

    Rel(extensionSystem, pipelineSystem, "Erweitert")
    Rel_U(extensionSystem, activityGraphModule, "Erweitert")

    Rel(settingsModule, databaseModule, "Verwendet")
    Rel(activityGraphModule, authUserModule, "Verwendet")
}

SHOW_LEGEND()
@enduml
