@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context Diagram für das ByteBunker System

Person(user, "Benutzer", "Interagiert mit dem System, lädt Daten hoch, verwendet die Visualiserungs- und Suchfunktionen.")

Enterprise_Boundary(bytebunker_boundary, "ByteBunker System") {
  System(bytebunker_pipeline, "Pipeline System", "ETL-Prozesse für Datenextraktion und -aggregation, Transformation und Speicherung.")
  System(bytebunker_activity_graph, "Aktivitäten in Graphdatenbank", "Speicherung für weitere Analyse")
  System(bytebunker_analysis, "Visualisierung & Analyse", "Erstellt Diagramme, Dashboards und Trends.")
  System(bytebunker_search, "Suche", "Ermöglicht das gezielte Finden von Aktivitäten und Daten.")
  System(bytebunker_statistics, "Statistiken", "Zeigt analytische Auswertungen der gesammelten Daten.")
}

System_Ext(google, "Google Takeout", "Exportierte Daten wie Standortverlauf, YouTube-Verlauf, Google Fit-Daten usw.")
System_Ext(spotify, "Spotify Datenexport", "Gespeicherte Musikhörverläufe und Präferenzen.")
System_Ext(photos, "Fotosammlung", "Gespeicherte persönliche Fotos zur Analyse und Erinnerung.")
System_Ext(browser, "Browser History", "Gespeicherter Web-Verlauf.")

Rel(user, bytebunker_pipeline, "Lädt Daten hoch, wertet Aktivitäten aus")
Rel(google, bytebunker_pipeline, "Datenquelle")
Rel(spotify, bytebunker_pipeline, "Datenquelle")
Rel(photos, bytebunker_pipeline, "Datenquelle")
Rel(browser, bytebunker_pipeline, "Datenquelle")

Rel(bytebunker_pipeline, bytebunker_activity_graph, "Speichern in Graphformat")
Rel(bytebunker_activity_graph, bytebunker_analysis, "Datenbereitstellung zur Analyse")
Rel(bytebunker_activity_graph, bytebunker_search, "Ermöglicht durchsuchbare Timeline und Inhalte")
Rel(bytebunker_activity_graph, bytebunker_statistics, "Erstellt statistische Auswertungen")

@enduml